betree/src/database/errors.rs
betree/src/database/mod.rs

This may be useful in situations (such as the benchmarks) where we specify the desired configuration externally. They currently require the `json` format, though `yaml` or perhaps `toml` would provide a better editability

database: add json serialize function for configuration

---

.github/workflows/ci.yml
betree/scripts/ci-test.sh
betree/tests/scripts/ci-test.sh

This PR adds a github action CI configuration for the `betree` crate.
Build, internal tests and integration tests will be executed in separate jobs and additionally give the name and output of each failed test including backtrace.

Add CI for `betree`

---

.github/workflows/ci.yml
README.md

This should allow us to cache dependencies across multiple runs.

workflows: Improve caching

---

julea-betree/src/lib.rs

At some point during the recent PRs this change went missing leading to an compilation error.

Fix julea-betree build usage

---

betree/tests/src/lib.rs

Some tests have been implemented to show that not all situations are solved optimally at the moment, and fail in the current state of the storage stack. Due to the long-term nature of solutions to resolve them, we indicate that they are expected to fail right now, so that the CI may properly interpret when new tests are failing.
Three tests (`write_overfull`, `write_delete_essential_size`, `overwrite_buffer`) are afflicted by this change, all related to how we handle out of storage situations in haura.
Additionally this PR updates the `write_overfull` case by removing cases depending on a previous internally used buffer growth factor.

Mark conceptual tests as expected failures

---

.github/workflows/ci.yml

This PR sets the `QUICKCHECK_TESTS` environment variable to a smaller value in the CI configuration. When running the tests this value is by default set to 100 which makes the testruns unbearably long (~20min) for relatively simple tests.
The `QUICKCHECK_TESTS` value determines the number of input variations which are used per test. If no variation fails, the test is considered successful. Given that large parts of our code base have experienced many iterations of tests already we probably don't need to worry too much when reducing this number to a more manageable workload in the CI.
This PR does not change anything in the normal developer experience, the default will still be used when executing tests locally.

ci: reduce number of quickcheck passes

---

betree/src/database/errors.rs
betree/src/object/mod.rs

At the moment we force a panic whenever key contain null bytes as we perform an assertion in the object interface on each access. Under many circumstances this is bad style and impacts stability when we run haura as part of a larger setup, for example in JULEA.

Object: return error when key contains illegal bytes

---

.github/workflows/ci.yml
betree/tests/scripts/ci-test.sh
betree/tests/scripts/test.sh

This PR improves and fixes a few small things in the separate test scripts. We ensure cleanup on errors or failed tests, also we include memory currently occupied by the system cache in the `num_threads` determination.

Improve test scripts

---

betree/src/object/mod.rs
betree/tests/src/object_store.rs

This PR partially modifies the public interface of the object store and allows some more internals to be tested with the "internal-api" feature. Mainly, we expose the iterator over object store ids to tests via the "internal-api" feature flag, to allow for init code testing as we perform when opening a database from storage.
Further, this PR adds a similar function to any user with `iter_object_store_names` which returns an iterator over all names of already created object stores. This can be handy when multiple stores are opened automatically for use-case with countless arbitrary stores such as per external-user or per application object stores.

Object: Expose Id handling with "internal-api" feature & Add Named Store Iterator

---

betree/src/database/dataset.rs
betree/src/lib.rs
betree/src/object/meta.rs
betree/src/object/mod.rs
betree/src/storage_pool/configuration.rs
betree/src/storage_pool/mod.rs
betree/src/storage_pool/unit.rs
betree/tests/src/configs.rs
betree/tests/src/object_store.rs

This PR contains a basic matching to utilize the already existing `PreferredAccessType` in the storage configuration with an additional creation mode for objects.
The user perspective looks similiar to the following snippet:
```rust
let obj = os.create_object_with_access_type(b"foo", PreferredAccessType::RandomWrite);
```
The access type is internally translated to a storage preference indicating the current rank. We might also want to add the access type to the object metadata for future reference.

Match access patterns from objects to tiers

---

.github/workflows/ci.yml
.github/workflows/pages.yml
README.md

The CI workflow currently reuses some Rust components present in the builder images. Clean them up properly before installing current Rust. It also fails if JULEA has been cached already, therefore do not include JULEA in the cache.
The Pages workflow currently fails if a cache exists already. Fix this and install mdBook using Cargo instead.

workflows: Improve CI and Pages workflows

---

betree/Cargo.toml
betree/benches/tree.rs
betree/src/buffer.rs
betree/src/cache/clock_cache.rs
betree/src/database/dataset.rs
betree/src/database/errors.rs
betree/src/database/mod.rs
betree/src/lib.rs
betree/src/migration/lfu.rs
betree/src/migration/mod.rs
betree/src/migration/msg.rs
betree/src/migration/reinforcment_learning.rs
betree/src/object/mod.rs
betree/src/storage_pool/storage_preference.rs
betree/src/tree/default_message_action.rs
betree/src/tree/errors.rs
betree/src/tree/imp/child_buffer.rs
betree/src/tree/imp/derivate_ref.rs
betree/src/tree/imp/flush.rs
betree/src/tree/imp/internal.rs
betree/src/tree/imp/leaf.rs
betree/src/tree/imp/mod.rs
betree/src/tree/imp/node.rs
betree/src/tree/imp/packed.rs
betree/src/tree/imp/range.rs
betree/src/tree/imp/split.rs
betree/src/tree/layer.rs
betree/src/tree/mod.rs

This PR contains some refactoring and reworking of the `tree` module. 
It largely aims to clean unclear paths and functions which were not documented. These changes are also used as the basis to a more general rework of the trait-to-structure design of *Haura* (They can be found under #32).
With the rework we also close some long open TODOs and FIXMEs, as well as clearing the pathways for node identification/access which we want to have for more fine grained accesses.
Summary:
- Fix & Document Tree Rebalancing Operations
- Copy Preferences on node split, if system preference is set
- Run internally-relevant asserts only in debug
- Extend Documentation & Visibility of the module
- Mitigate magic number use
- Extract general purpose impls into separate submodule
- Fix size updates when …

tree: cleanup

---

docs/src/SUMMARY.md
docs/src/rfc.md
docs/src/rfc/0-template.md
docs/src/rfc/1-pivotkey.md

- Title: Pivot Keys
- Status: *DRAFT*
This RFC adds an identifier which allows node defined access to structural
elements in the B-epsilon tree. This measure allows us to perform operations
which are more dependent on the actual present layout of the tree rather than
the semantic content which is stored by individual keys. Furthermore, in
combination with the recently added migration policies we gainthe option to
migrate singular nodes and improve the reporting scheme by using more stable
identifiers compared to the previously used `DiskOffset`s.
```ascii
p1      p2      p3
┌───────┬───────┬───────┬───────┐
│       │       │       │       │
│ Left  │ Right │ Right │ Right │
│ Outer │       │       │       │
└───┬───┴───┬───┴───┬───┴───┬───┘
│       │       │       │
▼       ▼       ▼ …
```

Add "Pivot Key" RFC Draft

---

bectl/src/main.rs
betree/src/data_management/dmu.rs
betree/src/data_management/impls.rs
betree/src/data_management/mod.rs
betree/src/database/dataset.rs
betree/src/database/handler.rs
betree/src/database/mod.rs
betree/src/database/root_tree_msg.rs
betree/src/database/snapshot.rs
betree/src/database/storage_info.rs
betree/src/metrics/mod.rs
betree/src/migration/mod.rs
betree/src/object/mod.rs
betree/src/storage_pool/disk_offset.rs
betree/src/storage_pool/mod.rs
betree/tests/src/lib.rs
betree/tests/src/object_store.rs

This PR implements two essential features, first it finalized space accounting previously introduced with #2 as it now also stores the disk space information in the root tree based on their 12bit global identifier. Second, this information is then used to start the Segment map search to find satisfying slots for the next allocation. This brings us a better scalability when not using Parity setups, second it allows for a more holistic overview of the current storage state, also helpful for user inspection.
In the process of this, we clean up the root tree keys by centralizing them in a separate module. Documentation for this is provided as module level documentation, easing the introduction of future keys.

Feature: Persist disk granular space accounting

---

bectl/Cargo.toml
betree/Cargo.toml
docs/src/fio-haura/run.md
julea-betree/Cargo.toml

This PR adds some additional documentation about external fragmentation observed in fio's random write benchmarks as well as tips how to reduce it.
In general, this doc just does some treatment of symptoms observed in practice. What should really be done is the resolution of fragmentation due to better allocations or tier-internal migration.

Improve documentation for fio

---

bectl/Cargo.toml
betree/Cargo.toml
fio-haura/src/fio-engine-haura.c
julea-betree/Cargo.toml

fio: check for proper maximum file size

---

betree/src/object/mod.rs
betree/tests/src/lib.rs

fix: optimize `read_at` in objects

---

betree/src/buffer.rs
betree/src/compression/mod.rs
betree/src/compression/none.rs
betree/src/compression/zstd.rs
betree/src/data_management/dmu.rs

Due to the usage of `AlignedStorage` and its Wrapper^n `Buf`  when storing and
serializing buffers length information is lost and the total length will simply
be set to the capacity. This is wrong. While serialization libraries seem to
handle this well enough, the decompression structure used from `zstd` did not
(This could be a bug though). This patch reworks the de/compression part to do 5
things:
- store the length of the original data alongside the compressed to ensure the
minimal amount of reallocation on decompression (1); before for each block a
reallocation happened bc of how the `zstd` decompression writer works
internally
- minimize the amount of copies during compression and decompression; the
`zstd` writer holds an internal buffer which, to my understanding, always
buffers the …

compression: fix decomp buffer mgt

---

.github/workflows/pages.yml

Version fights are happening when trying to install `mdbook-graphviz` with deps from `mdbook` to solve this we just pin the last minor from `mdbook`.

ci: fix mdbook-graphviz install

---

betree/src/allocator.rs
betree/src/data_management/dmu.rs
betree/src/database/handler.rs
betree/src/database/mod.rs
betree/tests/src/lib.rs

This commit changes the behavior of the database handler which manages the state of on-disk allocation bitmaps. The old behavior relied on keeping a single root node in cache to avoid consequent writebacks of updates inbetween sync's. An evicted root node with the current inter-sync data attached (e.g. bitmaps and size tracking info from the last root node writeback at the very end of the last sync which is written back to the superblock) would be in the "modified" state and therefore requiring a writeback when new entries should be added, this does two things it moves the node to the "in writeback" state, and it triggers a new allocation in the writeback sequence, which moves the node to the "modified" state and erases the writeback validity and thus restarting the cycle again. This …

handler: avoid repetitive bitmap writebacks on evict

---

betree/haura-benchmarks/Cargo.toml
betree/haura-benchmarks/haura-plots/haura_plots/__init__.py
betree/haura-benchmarks/haura-plots/haura_plots/ycsb_plots.py
betree/haura-benchmarks/run.sh
betree/haura-benchmarks/src/lib.rs
betree/haura-benchmarks/src/main.rs
betree/haura-benchmarks/src/ycsb.rs

This PR adds a simple IOPS test with the default YCSB-C configuration (Zipfian Distribution with theta 0.99 and 1 KB entries).
This benchmark does:
- multi-threaded read requests via key-value interface
- fetch the maximum number of IOPS reached for 1..n workers
This benchmark does not:
- split the 1KB into 10x100B members and access them separately
- rate limit requests to ascertain latencies
- gather latencies and tail latencies for a complete view of the request performance
This case was primarily added to compare between versions of Haura to estimate point query performance.

feat: Add simple ycsb-c-esque benchmark limit test

---

betree/src/database/mod.rs

This PR fixes a check which was meant to exclude arrays of length `>` 4  from the database configuration, but `<` was used as the reverse operation which lead to errors on some fallback configurations.

database: fix up length check of allocation strategy

---

betree/src/object/mod.rs

When reading small ranges this could lead to an error in the `read_at` stitch-cross-chunk-ranges-together code. Also improves overall efficiency as the previous fix (reading chunks + 1) could introduce at least 4MiB read amplification.

object: fix read range over chunks
